# Generated by Django 2.2.7 on 2019-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(max_length=100)),
                ('noidung', models.TextField()),
                ('ngaythem', models.DateTimeField(auto_now_add=True)),
                ('anh', models.ImageField(null=True, upload_to='')),
                ('gia', models.FloatField()),
            ],
        ),
    ]
